package de.stckoverflw.stckutils.util

import net.axay.kspigot.chat.KColors

object Colors {

    val PRIMARY = KColors.BLUE
    val SECONDARY = KColors.GRAY

    val ACTIVE = KColors.LIMEGREEN
    val INACTIVE = KColors.INDIANRED

    val ERROR = KColors.RED
    val ERROR_ARGS = INACTIVE
    val SUCCESS = KColors.DARKGREEN
    val SUCCESS_SECONDARY = ACTIVE

    val CONFIGURATION = KColors.MISTYROSE

    val CHALLENGE = KColors.ORANGERED
    val CHALLENGE_SECONDARY = KColors.ORANGE

    val CHALLENGE_COMPOUND = CHALLENGE
    val CHALLENGE_COMPOUND_SECONDARY = SECONDARY

    val GAME_CHANGE = KColors.ROYALBLUE
    val GAME_CHANGE_SECONDARY = KColors.DODGERBLUE

    val GAME_CHANGE_COMPOUND = GAME_CHANGE
    val GAME_CHANGE_COMPOUND_SECONDARY = SECONDARY

    val GOAL = KColors.DARKGOLDENROD
    val GOAL_SECONDARY = KColors.GOLD

    val GOAL_COMPOUND = GOAL
    val GOAL_COMPOUND_SECONDARY = SECONDARY

    val MORE_SETTINGS = KColors.AQUA
    val MORE_SETTINGS_SECONDARY = KColors.MEDIUMAQUAMARINE

    val WORLD_RESET_GUI = KColors.MEDIUMVIOLETRED
    val WORLD_RESET_GUI_SECONDARY = KColors.PALEVIOLETRED

    val TIMER_SETTINGS = KColors.PURPLE
    val TIMER_SETTINGS_SECONDARY = KColors.MEDIUMPURPLE

    val TIMER_ITEM = KColors.INDIGO
    val TIMER_ITEM_SECONDARY = SECONDARY

    val TIMER_DIRECTION = KColors.PURPLE

    val VILLAGE_SPAWN = KColors.SADDLEBROWN
    val VILLAGE_SPAWN_SECONDARY = KColors.ROSYBROWN

    val GOAL_TYPE = KColors.ORANGE
    val GOAL_TYPE_SECONDARY = SECONDARY

    val JOIN_WHILE_RUNNING = KColors.DARKOLIVEGREEN
    val JOIN_WHILE_RUNNING_SECONDARY = SECONDARY

    val RESET = KColors.DARKRED
    val RESET_SECONDARY = SECONDARY

    val COLOR_COMPOUND_SECONDARY = SECONDARY

    val WORLD_RESET = KColors.DARKRED
    val WORLD_RESET_SECONDARY = SECONDARY

    val TIMER_COLOR = KColors.VIOLET
    val TIMER_COLOR_SECONDARY = SECONDARY

    val SETTINGS = ACTIVE

    val ACCENT_AQUA = KColors.AQUAMARINE

    val GO_BACK = KColors.AQUA
    val GO_BACK_SECONDARY = KColors.MEDIUMAQUAMARINE
}
